# Generated by Django 3.1.5 on 2021-03-24 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InfluencerMarketPlace', '0002_auto_20210314_1847'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=120)),
                ('reciever', models.CharField(max_length=120)),
                ('msg_content', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField()),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InfluencerMarketPlace.conversation')),
            ],
        ),
        migrations.AddField(
            model_name='userinfo',
            name='conversation',
            field=models.ManyToManyField(to='InfluencerMarketPlace.Conversation'),
        ),
    ]
