# Generated by Django 3.1.5 on 2021-03-25 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InfluencerMarketPlace', '0003_auto_20210323_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='FacebookName',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='TikTokName',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='cars'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='socialActivated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='msg_content',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='reciever',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='InstaName',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
