# Generated by Django 3.1.5 on 2021-03-25 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InfluencerMarketPlace', '0004_auto_20210324_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='conversation',
            field=models.ManyToManyField(blank=True, to='InfluencerMarketPlace.Conversation'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='interests',
            field=models.ManyToManyField(blank=True, to='InfluencerMarketPlace.Interest'),
        ),
    ]
