# Generated by Django 3.1.5 on 2021-03-26 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InfluencerMarketPlace', '0005_auto_20210324_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='activationCode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='activationPlatform',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='activationTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='Cost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='FollowerCount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
