# Generated by Django 3.1.5 on 2021-03-31 15:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('InfluencerMarketPlace', '0006_auto_20210326_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='name',
        ),
        migrations.AddField(
            model_name='conversation',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
