# Generated by Django 3.2.3 on 2021-05-20 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InfluencerMarketPlace', '0008_auto_20210331_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='account_type',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
